# Generated by Django 5.1.7 on 2025-03-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEtiqueta',
            fields=[
                ('detalle_etiqueta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('etiqueta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('etiqueta', models.CharField(max_length=50, unique=True, verbose_name='Etiqueta')),
                ('color', models.CharField(blank=True, max_length=6, null=True, verbose_name='Color')),
            ],
        ),
    ]
