# Generated by Django 5.1.7 on 2025-03-13 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etiquetas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalleetiqueta',
            name='etiqueta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etiquetas.etiqueta', verbose_name='Etiqueta'),
        ),
    ]
