# Generated by Django 5.2 on 2025-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etiquetas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color'),
        ),
    ]
