# Generated by Django 5.2 on 2025-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporizadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('horas', models.IntegerField(default=0)),
                ('minutos', models.IntegerField(default=25)),
                ('segundos', models.IntegerField(default=0)),
                ('uuid', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(default=0)),
            ],
        ),
    ]
