# Generated by Django 5.2 on 2025-04-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pomodoro', '0002_temporizadores_usuario_id'),
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesiones', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('tarea_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tareas.tarea', verbose_name='Tarea')),
            ],
        ),
    ]
