# Generated by Django 5.1.7 on 2025-03-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('titulo', models.CharField(max_length=50, verbose_name='Tarea')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.IntegerField(default=0, verbose_name='Estado')),
                ('es_importante', models.BooleanField(default=False, verbose_name='¿Es importante?')),
                ('es_urgente', models.BooleanField(default=False, verbose_name='¿Es urgente?')),
                ('fecha_vencimiento', models.DateField(null=True, verbose_name='Fecha de vencimiento')),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
